version: '3.8'

services:
  app:
    build: .
    ports:
      - "8088:8088"
    container_name: location-server
    restart: always

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok-tunnel
    command: http app:8088
    environment:
      NGROK_AUTHTOKEN: "NGROK_TOKEN"
    depends_on:
      - app
